<?xml version="1.0"?>
<testResults>
  <FitNesseVersion>v20140122</FitNesseVersion>
  <rootPath>DbFit.AnonymousBlock</rootPath>
    <result>
    <counts>
      <right>0</right>
      <wrong>0</wrong>
      <ignores>0</ignores>
      <exceptions>2</exceptions>
    </counts>
    <runTimeInMillis>584</runTimeInMillis>
    <content>&lt;br/&gt;&lt;span class="meta"&gt;classpath: lib/*.jar&lt;/span&gt;&lt;br/&gt;&lt;br/&gt;&lt;table&gt;
	&lt;tr&gt;
		&lt;td&gt;import fixture&lt;/td&gt;
	&lt;/tr&gt;
	&lt;tr&gt;
		&lt;td&gt;dbfit.fixture&lt;/td&gt;
	&lt;/tr&gt;
&lt;/table&gt;
&lt;br/&gt;&lt;table&gt;
	&lt;tr&gt;
		&lt;td class="error"&gt;DatabaseEnvironment&lt;hr&gt;&lt;pre&gt;&lt;div class="fit_stacktrace"&gt;java.lang.Error: Cannot load Oracle database driver oracle.jdbc.OracleDriver. Is the JDBC driver on the classpath?
	at dbfit.api.DbEnvironmentFactory$EnvironmentDescriptor.checkDriver(DbEnvironmentFactory.java:45)
	at dbfit.api.DbEnvironmentFactory$EnvironmentDescriptor.createEnvironmentInstance(DbEnvironmentFactory.java:60)
	at dbfit.api.DbEnvironmentFactory.createEnvironmentInstance(DbEnvironmentFactory.java:102)
	at dbfit.api.DbEnvironmentFactory.newEnvironmentInstance(DbEnvironmentFactory.java:106)
	at dbfit.fixture.DatabaseEnvironment.setDatabaseEnvironment(DatabaseEnvironment.java:27)
	at dbfit.fixture.DatabaseEnvironment.doTable(DatabaseEnvironment.java:20)
	at fit.Fixture.interpretFollowingTables(Fixture.java:120)
	at fit.Fixture.interpretTables(Fixture.java:106)
	at fit.Fixture.doTables(Fixture.java:80)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
Caused by: java.lang.ClassNotFoundException: oracle.jdbc.OracleDriver
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at dbfit.api.DbEnvironmentFactory$EnvironmentDescriptor.checkDriver(DbEnvironmentFactory.java:43)
	... 11 more
&lt;/div&gt;&lt;/pre&gt;&lt;/td&gt;
		&lt;td colspan="4"&gt;oracle&lt;/td&gt;
	&lt;/tr&gt;
	&lt;tr&gt;
		&lt;td&gt;connect&lt;/td&gt;
		&lt;td&gt;127.0.0.1:7771&lt;/td&gt;
		&lt;td&gt;CID_OWNER&lt;/td&gt;
		&lt;td&gt;cid_owner&lt;/td&gt;
		&lt;td&gt;CDPDVS01&lt;/td&gt;
	&lt;/tr&gt;
&lt;/table&gt;
&lt;br/&gt;&lt;table&gt;
	&lt;tr&gt;
		&lt;td class="error"&gt;Execute&lt;hr&gt;&lt;pre&gt;&lt;div class="fit_stacktrace"&gt;java.lang.Error: java.lang.NullPointerException
	at dbfit.fixture.Execute.doRows(Execute.java:29)
	at fit.Fixture.doTable(Fixture.java:154)
	at fit.Fixture.interpretFollowingTables(Fixture.java:120)
	at fit.Fixture.interpretTables(Fixture.java:106)
	at fit.Fixture.doTables(Fixture.java:80)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
Caused by: java.lang.NullPointerException
	at dbfit.api.DbStatement.buildPreparedStatement(DbStatement.java:23)
	at dbfit.fixture.Execute.doRows(Execute.java:26)
	... 7 more
&lt;/div&gt;&lt;/pre&gt;&lt;/td&gt;
		&lt;td&gt; 
declare
cursor c is select table_name from user_tables where table_name IN (
  
                            'WIZARD',
                            'WIZARD_COMPONENTS_DISABLE'                                   
                            );
v_err_msg varchar2(3000);
v_stmt varchar2(3000);
v_stmt1 varchar2(3000);
v_cnt number := 1;
v_row_cnt number:=0;

BEGIN

FOR rec IN c

LOOP
    BEGIN
    v_stmt1 := 'select count(1) from '||rec.table_name||' where rownum = 1 ';
    DBMS_OUTPUT.PUT_LINE('stmt1:'||v_stmt1);
    -- EXECUTE IMMEDIATE 'select count(1) into v_cnt from '||rec.table_name||' where rownum = 1 ';-- returning into v_cnt;
    EXECUTE IMMEDIATE v_stmt1 into v_cnt;
     if v_cnt=0 then
    v_stmt := 'insert /*+ APPEND */ into '||rec.table_name ||'(select * from CID_OWNER.'||rec.table_name||')';
    --DBMS_OUTPUT.PUT_LINE('inside if');
    EXECUTE IMMEDIATE v_stmt;
    v_row_cnt:=sql%rowcount;
      dbms_output.Put_line(' Number of record inserted : '||v_row_cnt);
    
   --DBMS_OUTPUT.PUT_LINE('inside if 2');
    COMMIT;
    
    ELSE
     dbms_output.put_line(' Data already present in Table name  '||rec.table_name);
    END IF;
      
    EXCEPTION
    WHEN OTHERS THEN
        v_err_msg := SUBSTR(SQLERRM,1,200);
        DBMS_OUTPUT.PUT_LINE(' Following error occurred for table '||rec.table_name||' : '||v_err_msg);
    
    END;
  
END LOOP;
END;
&lt;/td&gt;
	&lt;/tr&gt;
&lt;/table&gt;
</content>
    <relativePageName>AnonymousBlock</relativePageName>
    
    
    
  </result>
  
    <finalCounts>
    <right>0</right>
    <wrong>0</wrong>
    <ignores>0</ignores>
    <exceptions>1</exceptions>
  </finalCounts>
  <totalRunTimeInMillis>1252</totalRunTimeInMillis>
  
</testResults>

