<?xml version="1.0"?>
<testResults>
  <FitNesseVersion>v20140122</FitNesseVersion>
  <rootPath>DbFit.AnonymousBlock</rootPath>
    <result>
    <counts>
      <right>0</right>
      <wrong>0</wrong>
      <ignores>0</ignores>
      <exceptions>1</exceptions>
    </counts>
    <runTimeInMillis>1294</runTimeInMillis>
    <content>&lt;br/&gt;&lt;span class="meta"&gt;classpath: lib/*.jar&lt;/span&gt;&lt;br/&gt;&lt;br/&gt;&lt;table&gt;
	&lt;tr&gt;
		&lt;td&gt;import fixture&lt;/td&gt;
	&lt;/tr&gt;
	&lt;tr&gt;
		&lt;td&gt;dbfit.fixture&lt;/td&gt;
	&lt;/tr&gt;
&lt;/table&gt;
&lt;br/&gt;&lt;table&gt;
	&lt;tr&gt;
		&lt;td&gt;DatabaseEnvironment&lt;/td&gt;
		&lt;td colspan="4"&gt;oracle&lt;/td&gt;
	&lt;/tr&gt;
	&lt;tr&gt;
		&lt;td&gt;connect&lt;/td&gt;
		&lt;td&gt;127.0.0.1:7771&lt;/td&gt;
		&lt;td&gt;CID_OWNER&lt;/td&gt;
		&lt;td&gt;cid_owner&lt;/td&gt;
		&lt;td&gt;CDPDVS01&lt;/td&gt;
	&lt;/tr&gt;
&lt;/table&gt;
&lt;br/&gt;&lt;table&gt;
	&lt;tr&gt;
		&lt;td class="error"&gt;Execute&lt;hr&gt;&lt;pre&gt;&lt;div class="fit_stacktrace"&gt;java.lang.Error: java.sql.SQLException: ORA-06550: line 1, column 1372:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:

   ( begin case declare end exception exit for goto if loop mod
   null pragma raise return select update while with
   &lt;an identifier&gt; &lt;a double-quoted delimited-identifier&gt;
   &lt;a bind variable&gt; &lt;&lt; continue close current delete fetch lock
   insert open rollback savepoint set sql execute commit forall
   merge pipe purge

	at dbfit.fixture.Execute.doRows(Execute.java:29)
	at fit.Fixture.doTable(Fixture.java:154)
	at fit.Fixture.interpretFollowingTables(Fixture.java:120)
	at fit.Fixture.interpretTables(Fixture.java:106)
	at fit.Fixture.doTables(Fixture.java:80)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
Caused by: java.sql.SQLException: ORA-06550: line 1, column 1372:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:

   ( begin case declare end exception exit for goto if loop mod
   null pragma raise return select update while with
   &lt;an identifier&gt; &lt;a double-quoted delimited-identifier&gt;
   &lt;a bind variable&gt; &lt;&lt; continue close current delete fetch lock
   insert open rollback savepoint set sql execute commit forall
   merge pipe purge

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:113)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:754)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:972)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1192)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3415)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3521)
	at dbfit.fixture.StatementExecution.run(StatementExecution.java:75)
	at dbfit.fixture.Execute.doRows(Execute.java:27)
	... 7 more
&lt;/div&gt;&lt;/pre&gt;&lt;/td&gt;
		&lt;td&gt; 
declare
cursor c is select table_name from user_tables where table_name IN (
  
                            'WIZARD',
                            'WIZARD_COMPONENTS_DISABLE'                                   
                            );
v_err_msg varchar2(3000);
v_stmt varchar2(3000);
v_stmt1 varchar2(3000);
v_cnt number := 1;
v_row_cnt number:=0;

BEGIN

FOR rec IN c

LOOP
    BEGIN
    v_stmt1 := 'select count(1) from '||rec.table_name||' where rownum = 1 ';
    DBMS_OUTPUT.PUT_LINE('stmt1:'||v_stmt1);
    -- EXECUTE IMMEDIATE 'select count(1) into v_cnt from '||rec.table_name||' where rownum = 1 ';-- returning into v_cnt;
    EXECUTE IMMEDIATE v_stmt1 into v_cnt;
     if v_cnt=0 then
    v_stmt := 'insert /*+ APPEND */ into '||rec.table_name ||'(select * from CID_OWNER.'||rec.table_name||')';
    --DBMS_OUTPUT.PUT_LINE('inside if');
    EXECUTE IMMEDIATE v_stmt;
    v_row_cnt:=sql%rowcount;
      dbms_output.Put_line(' Number of record inserted : '||v_row_cnt);
    
   --DBMS_OUTPUT.PUT_LINE('inside if 2');
    COMMIT;
    
    ELSE
     dbms_output.put_line(' Data already present in Table name  '||rec.table_name);
    END IF;
      
    EXCEPTION
    WHEN OTHERS THEN
        v_err_msg := SUBSTR(SQLERRM,1,200);
        DBMS_OUTPUT.PUT_LINE(' Following error occurred for table '||rec.table_name||' : '||v_err_msg);
    
    END;
  
END LOOP;
END;
&lt;/td&gt;
	&lt;/tr&gt;
&lt;/table&gt;
</content>
    <relativePageName>AnonymousBlock</relativePageName>
    
    
    
  </result>
  
    <finalCounts>
    <right>0</right>
    <wrong>0</wrong>
    <ignores>0</ignores>
    <exceptions>1</exceptions>
  </finalCounts>
  <totalRunTimeInMillis>1721</totalRunTimeInMillis>
  
</testResults>

